name: appo
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.7.2


dependencies:
  android_id: ^0.4.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter
  http: ^0.13.6
  url_launcher: ^6.2.5
  intl: ^0.19.0
  path_provider: ^2.1.2
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  flutter_localizations:
    sdk: flutter
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  workmanager:
    git:
      url: https://github.com/vrtdev/flutter_workmanager.git
      path: workmanager
      ref: main
  cupertino_icons: ^1.0.8
  
dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon.png"
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true